resource_types:
  - name: webhook
    type: registry-image
    privileged: true
    source:
      repository: batlefroc/concourse-discord
      tag: latest

resources:
  - name: discourd
    type: webhook
    icon: bell
    source:
      webhook: https://discord.com/api/webhooks/902523987391819806/WoGNHGGJWaXW37PldOTlFQc-nyjZ8HA8Bz7xQl-yYAAX3lBSi1cwcnt39RloZ4DlnmKn

jobs:
  - name: test_webhook
    public: true
    plan:
      - task: truc
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: node
              tag: buster
          run:
            path: sh
            args:
              - -exc
              - |
                echo "test"
      - put: discourd
