#! /usr/bin/env node
import { getStdinAsJson, getColor } from "./common.js";
import webhook from "webhook-discord";
async function out() {
  try {
    var conf = await getStdinAsJson();
    const Hook = new webhook.Webhook(conf.source.webhook);
    const msg = new webhook.MessageBuilder()
      .setName("WeeboCI")
      .setTime(Date.now())
      .setColor(getColor(conf.status))
      .setTitle("test")
      .setText("This is my webhook!");
    Hook.send(msg);
  } catch (e) {
    console.log(e);
  }
  console.log(conf);
}

out();
