#! /usr/bin/env node
const webhook = require("webhook-discord");
const { stdin } = process;
async function getStdin() {
  let result = "";

  if (stdin.isTTY) {
    return result;
  }

  stdin.setEncoding("utf8");

  for await (const chunk of stdin) {
    result += chunk;
  }

  return result;
}

getStdin.buffer = async () => {
  const result = [];
  let length = 0;

  if (stdin.isTTY) {
    return Buffer.concat([]);
  }

  for await (const chunk of stdin) {
    result.push(chunk);
    length += chunk.length;
  }

  return Buffer.concat(result, length);
};

async function getStdinAsJson() {
  var result;
  try {
    var truc = await getStdin();
    console.log(truc);
    result = JSON.parse(truc);
  } catch (err) {
    console.error("Error thrown during parsing stdin!");
    throw err;
  }
  return result;
}

function getColor(value) {
  switch (String(value).toLowerCase()) {
    case "success":
      return "#1A4314";
    case "failed":
    case "errored":
    case "aborted":
      return "#800000";
    default:
      return "#FFFFFF";
  }
}

async function out() {
  try {
    var conf = await getStdinAsJson();
    console.log(conf);
    const Hook = new webhook.Webhook(conf.source.webhook);
    const msg = new webhook.MessageBuilder()
      .setName("WeeboCI")
      .setTime(Date.now())
      .setColor(getColor(conf.status))
      .setTitle("test")
      .setText("This is my webhook!");
    Hook.send(msg);
  } catch (e) {
    console.log(e);
  }
}

out();
